const { Router } = require("express");
const controller = require("./controller");
const payment = require("./paymentcontroller");
const router = Router();
router.get("/info", controller.getstudent);
router.post("/login", controller.login);
router.post("/signup", controller.signup);
router.post("/leavereq", controller.leave_request);
router.get("/getstudentclass/:classid", controller.getstudentclass);
router.get("/getmessages/:class_subject_id", controller.getmessages);
router.get("/getclasstimetable/:classid", controller.getclasstimetable);
router.get("/wholeclasstimetable/:classid", controller.wholetimetable);
router.get("/getstudentattendance/:studentid", controller.getstudentattendance);
router.get("/getclasssubjects/:classid", controller.getclasssubjects);
router.get("/dailyattendance/:studentid", controller.dailyattendance);
router.get("/getquizes/:studentid", controller.getquizes);
router.get("/getassignments/:studentid", controller.getassignments);
router.get("/studentfee/:studentid", controller.studentfee);
router.get("/studentposts", controller.studentposts);
router.get("/transactions/:studentid", controller.studenttransactions);
router.get("/getquizquestions/:quizid", controller.getquizquestions);
router.post("/submitanswers", controller.submitanswers);
router.post("/getreport", controller.getreport);
router.get("/getexamnames", controller.getexamnames);
router.post("/examdetails", controller.examdetails);
router.get("/recentquiz/:studentid", controller.recentquiz);
router.post("/quizresult", controller.resultpage);
router.get("/assignmentinfo/:assignment_id", controller.assignmentinfo);
router.post("/payment", payment.getpay);
router.get("/recent", payment.getRecentTransactions);
router.post("/status", payment.getstatus);
module.exports = router;
